blank_issues_enabled: false
contact_links:
    - name: Dussicord Support Server
      url: https://equicord.org/discord
      about: If you need help regarding Dussicord, please join our support server!
    - name: Dussicord Installer
      url: https://github.com/Dussicord/Equilotl
      about: You can find the Dussicord Installer here
